import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "InterviewEdge AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider afterSignInUrl="/dashboard">
      <html lang="en">
        <body
          className={inter.className}
        >
          
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
